version: '3.3'

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432

  backend:
    image: noble6/user_rest_api:latest
    restart: always
    volumes:
      - static_value:/code/static/root/
    depends_on:
      - db

  nginx:
    image: nginx:1.18.0
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/:/code/ssl/
      - static_value:/code/static/root/
    depends_on:
      - backend

volumes:
  postgres_data:
  static_value: